name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -   name: Docker Login
        uses: docker/login-action@v2
        with:
          username: jebitomi
          password: ${{ secrets.dockerpw }}
          
    - name: Build the Docker image
      run: |
          docker build ./samplewebapp --file samplewebapp/Dockerfile --tag JebiTomi/samplewebapp:latest
          docker push JebiTomi/samplewebapp:latest
